# Generated by Django 3.0.7 on 2020-06-28 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
