# Generated by Django 3.0.7 on 2020-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200623_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_for',
            field=models.TextField(null=True),
        ),
    ]
