# Generated by Django 3.0.7 on 2020-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_reply_reply_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_for',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
