# Generated by Django 3.0.7 on 2020-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200624_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_for',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
